### ISSUE TITLE
Adding Non-Docker Hosts

### ISSUE THREAD

**Issue by gatesry** [erikespinoza/v4raider#3]
Hi Erik,

First! - Thank you very much for the guide. **Do you have any links to buy you a coffee/beer?** 

I was able to get everything set up and running smoothly for the Traefik Dashboard/WireGuard services. I'm curious if you have any suggestions on adding external servers to the proxy manager? Looking at your [Other Containers](https://github.com/erikespinoza/v4raider#what-about-other-containers) section, and don't know if this would work for external non-docker hosts that live outside the `DMZ` network.

I've added a dynamic .yml file for one service that points to my LAN (e.g. 192.168.1.X) and corrected any errors in the dashboard. 

![image](https://user-images.githubusercontent.com/67442967/113510760-e9913880-9521-11eb-9ccb-59935b6c29f3.png)

**app-unifi.yml**

```
http:
  routers:
    unifi-rtr:
      rule: "HostHeader(`unifi.mydomain.com`)" 
      entryPoints:
        - https
      middlewares:
        - middlewares-basic-auth@file
      service: unifi-svc

  services:
    unifi-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.1.3:8443"
 ```

**middlewares.yml**

```
http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
         users:
           - "user:$ABCDEFGHIJK/LMNOP"
```

**Dashboard Screenshot**

![image](https://user-images.githubusercontent.com/67442967/113510600-3aecf800-9521-11eb-9cec-25f10e7cbc71.png)

With all the above set, I just get a generic browser error in Edge saying it can't reach this domain.

_If this is out of scope, please feel free to close._

Thank you
